# Generated by Django 3.0.8 on 2020-11-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20201126_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
